---

- name: Hardening Distros and Services
  hosts: all

  vars_files:
    - vars/custom.yaml

  roles:
    - { role: custom-ssh-user, tags: custom-ssh-user }
    - { role: update-distro, tags: update-distro }
    - { role: jnv.unattended-upgrades, tags: unattended-upgrades }
    - { role: dev-sec.os-hardening, tags: os-hardening }
    - { role: dev-sec.ssh-hardening, tags: ssh-hardening }
    - { role: oefenweb.fail2ban, tags: fail2ban }
